### ISSUE TITLE
Blocked for more than 120 seconds.

### ISSUE THREAD

**Issue by isvaljek** [gael-ian/vagrant-bindfs#68] opened 2016-12-22 15:04 UTC
I get this error when I vagrant up with vagrant-bindfs + vagrant-winnfsd:
```
Ubuntu 16.04.1 LTS vagrant tty1
vagrant login: [ 840.061101] INFO: task bindfs:2930 blocked for more than 120 seconds. [ 840.061136]	Tainted: G	OE 4.4.0-31-generic #50-Ubuntu
[ 840.061152] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

This is with Roots.io Trellis + Bedrock (WordPress), it just hangs at the Trellis line:
Install Dependencies with Composer.

I guess it is the first time that Trellis tries to connect to host disk, but I'm not sure about this.

This is on Windows 10 Pro x64, VirtualBox 5.1 and Vagrant 1.9.1, and latest Vagrant plugins after vagrant plugin update

**Comment by gael-ian** [comment] 2016-12-22 21:17
Hi @isvaljek,

It's hard to be categoric just with this little part of Vagrant output but the problem seems to be that Vagrant is waiting for you to give login informations to connect to your guest OS and finally give up. So you probably guess right.

That also means that the problem is nothing with vagrant-bindfs but more with Trellis itself. Can you check to Trellis documentation and see if you don't miss anything? (as a private SSH key for example) or maybe open an issue on the Trellis github project.

I close this issue as I don't think it is related to the plugin but feel free to reopen it if I'm wrong.

Thanks

**Closed** 2016-12-22 21:17 UTC
